name: mobile_bangking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.5
  multiavatar: ^0.1.5
  badges: ^3.1.1
  collection: ^1.17.0
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  packages :
    git :
      url : https://github.com/rahmat999ht/packages.git
  card_swiper: ^2.0.4
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
     - assets/images/

