// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Qzkk2f4a5MEfhbDnZ2uBKEGpEZFswvg',
    appId: '1:123594767156:android:592abb149af21801654361',
    messagingSenderId: '123594767156',
    projectId: 'mobile-banking-386ee',
    storageBucket: 'mobile-banking-386ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFKMdv9-LGNajCuJV-hUbbotj_igPM9zk',
    appId: '1:123594767156:ios:76e08c2c69ba34ce654361',
    messagingSenderId: '123594767156',
    projectId: 'mobile-banking-386ee',
    storageBucket: 'mobile-banking-386ee.appspot.com',
    iosClientId:
        '123594767156-en3ivjel22igp5pqjucli0ioh08t03q4.apps.googleusercontent.com',
    iosBundleId: 'com.yayat.mobileBangking',
  );
}
